# Generated by Django 3.1.2 on 2020-10-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('book_class', models.CharField(choices=[('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SSS1', 'SSS1'), ('SSS2', 'SSS2'), ('SSS3', 'SSS3')], max_length=255)),
                ('subjects', models.CharField(default='Mathematics', max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('edition', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='e_library/images')),
                ('book', models.FileField(blank=True, upload_to='e_library/pdfs')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
