# Generated by Django 3.1.2 on 2020-10-01 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priviledge', models.BooleanField(default=True)),
                ('subjects_taught', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('religion', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('class_taught', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, default='registration/images/0011.jpg', upload_to='registration/images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('father_occupation', models.CharField(max_length=255)),
                ('student_class', models.CharField(choices=[('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SSS1', 'SSS1'), ('SSS2', 'SSS2'), ('SSS3', 'SSS3')], max_length=255)),
                ('admission_date', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('picture', models.ImageField(blank=True, default='registration/images/0011.jpg', upload_to='registration/images')),
                ('parent_contact', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
