# Generated by Django 3.1.2 on 2020-10-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(default='registration/images/0011.jpg', null=True, upload_to='registration/images'),
        ),
    ]
