# Generated by Django 3.1.2 on 2020-11-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20201018_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='school_fee',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
